# docker-compose.yml
version: '3'
services:
  rails-db:
    image: postgres
    container_name: rails-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - DATABASE_HOST=db-host
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - networks
    ports:
      - "5432:5432"
  rails-web:
    build: .
    container_name: rails-web
    volumes:
      - .:/docker-rails
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - rails-db
    networks:
      - networks
volumes:
  rails-web:
  rails-db:
networks:
  networks:
    driver: bridge
